# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#version
version: "1.0"


title: Long Gong@CS.GaTech
email: gonglong.gatech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First play with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lgong30.github.io/"
# "http://localhost:8089" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lgong30
github_username:  lgong30
duoshuo_shortname: lgong
# Build settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

markdown: kramdown
#kramdown:
#  input: GFM
highlighter: rouge


# 分页设置
paginate: 10
paginate_path: "blog/page:num/"




# Customized variables
research_interests:
  - scheduling for crossbar switches
  - switching in data center networks
  - data streaming
  - online social networking
  - software defined networking
  - network function virtualization
  - programmable switch
  - scheduling in wireless networks
  

advisor:
  MS:
    name: Zuqing Zhu
    url: http://www.zuqingzhu.info/
  PhD:
    name: Jun (Jim) Xu
    url: http://www.cc.gatech.edu/~jx/

author:
  full_name: Long Gong
  role: Research Assistant
  email: long.github@gmail.com
  edu_email: gonglong@gatech.edu
  edu_email_display: "gonglong@gatech.edu"
  url: cc.gatech.edu/~lgong30
  github: github.com/saber-dragon
  web: lgong30.github.io
  linkedin: linkedin.com/in/long-gong-14292859

education:
  - edu3:
    institution: Georgia Institution of Technology
    address: Atlanta, GA, USA 
    degree: Ph.D.
    major: Computer Science
    started: 2015
    duration: (2015 - 2019)
    description: "" 
  - edu2:
    institution: University of Science and Technology of China (USTC)
    address: Hefei, Anhui, China
    degree: M.E.
    major: Electronic Engineering
    started: 2012
    duration: (2012 - 2015)
    description: ""
  - edu1:
    institution: University of Science and Technology of China (USTC)
    address: Hefei, Anhui, China
    degree: B.E.
    major: Electronic Engineering
    started: 2008
    duration: (2008 - 2012)
    description: ""

news:
  - summary: Papers Got Accepted 
    time: May. 12, 2018
    content: Two of our papers on hybrid switching got accepted by IEEE Cloud and Cloud, respectively.
  - summary: Webpage Updated 
    time: Sept. 5, 2017
    content: Latest resume of Long is available!!!
  - summary: Webpage Updated
    time: Sept. 2, 2017
    content: 1. Add course info<br/>2. Update reviewer info<br/>3. CV will be available ASAP!!!
  - summary: Paper Got Rejected
    time: Sept. 2, 2017
    content: Unfornately, our paper on hybrid switching got rejected by IFIF Performance 2017.
  - summary: Student Travel Grant Award
    time: May 23, 2017
    content: Long got the Student Travel Grant Award for SIGMETRICS 2017
  - summary: Paper Accepted
    time: May 23, 2017
    content: Our work on online social networking will appear in ICCCN 2017 as an invited paper
  - summary: Unmatched in Google's Host Matching
    time: April 10, 2017
    content: Unfortunately, Long failed to match with a team in the host matching stage for the internship position at Google. 
  - summary: Qualifying Exam Passed
    time: April 4, 2017
    content: Long passed his qualifying exam, becoming a PhD candidate
  - summary: Webpage Updated
    time: April 4, 2017
    content: "Adopted the Orbit template designed by <a href=\"\" target=\"_blank\">Xiaoying Riley</a>"
  - summary: Webpage Updated
    time: March 25, 2017
    content: Update publication page
  - summary: Webpage Updated
    time: March 23, 2017
    content: "1. Add news panel to the index page of my website<br/>2. Update about page<br/>3. Add recent projects"
  - summary: Paper Accepted
    time: March 22, 2017
    content: "Our paper <I>Queue-Proportional Sampling: A Better Approach to Crossbar Scheduling for Input-Queued Switches</I> was accepted by <a href=\"https://www.sigmetrics.org/sigmetrics2017/\">Sigmetrics 2017</a>"
  - summary: Useful Tutorial Found
    time: March 20, 2017
    content: "\"Discover\" <a href=\"https://www.youtube.com/watch?v=rYW7kQRyUvA\">a very useful tutorial on Open vSwitch</a> on YouTuBe, which shows how to connect two VMs through OVS bridge"

publications:
  - pub5:
    title: "2-Hop Eclipse: A Fast Algorithm for Bandwidth-Efficient Data Center Switching"
    authors: ["Liang Liu", "Long Gong", "Sen Yang", "Jun (Jim) Xu", "Lance Fortnow"]
    conference: 2018 International Conference on Cloud Computing (CLOUD 2018)
    url: http://icws.org/2018/resources/SCF2018-AP-0606.pdf
  - pub4:
    title: "Best First Fit (BFF): An Approach to Partially Reconfigurable Hybrid Circuit and Packet
Switching"
    authors: ["Liang Liu", "Long Gong", "Sen Yang", "Jun (Jim) Xu", "Lance Fortnow"]
    conference: IEEE CLOUD 2018
    url: http://conferences.computer.org/services/2018/assets/files/IEEECongress_techprogram_CHAIRS.pdf
  - pub3:
    title: "Queue-Proportional Sampling: A Better Approach to Crossbar Scheduling for Input-Queued Switches"
    authors: ["Long Gong", "Paul Tune", "Liang Liu", "Sen Yang", "Jun (Jim) Xu"]
    conference: ACM SIGMETRICS 2017
    url: https://dl.acm.org/citation.cfm?id=3084440
    type: conference
    pdf: http://www.cc.gatech.edu/classes/AY2017/cs7260_spring/qps-switching.pdf
  - pub2:
    title: Impairment- and Splitting-Aware Cloud-Ready Multicast Provisioning in Elastic Optical Networks
    authors: ["Zuqing Zhu", "Xiahe Liu", "Yixiang Wang", "Wei Lu", "Long Gong", "Shui Yu", "Nirwan Ansari"]
    journal: IEEE/ACM Transactions on Networking
    url: http://ieeexplore.ieee.org/abstract/document/7731159/
    type: journal
    pdf: http://zuqingzhu.info/pub_doc/2016/IEEE_TON_RMSA_multicast_Final.pdf
    abstract: It is known that multicast provisioning is important for supporting cloud-based applications, and as the traffics from these applications are increasing quickly, we may rely on optical networks to realize high-throughput multicast. Meanwhile, the flexible-grid elastic optical networks (EONs) achieve agile access to the massive bandwidth in optical fibers, and hence can provision variable bandwidths to adapt to the dynamic demands from the cloud-based applications. In this paper, we consider all-optical multicast in EONs in a practical manner and focus on designing impairment- and splitting-aware multicast provisioning schemes. We first study the procedure of adaptive modulation selection for a light-tree, and point out that the multicast scheme in EONs is fundamentally different from that in the fixed-grid wavelength-division multiplexing networks. Then, we formulate the problem of impairment- and splitting-aware routing, modulation and spectrum assignment (ISa-RMSA) for all-optical multicast in EONs and analyze its hardness. Next, we analyze the advantages brought by the flexibility of routing structures and discuss the ISa-RMSA schemes based on light-trees and light-forests. This paper suggests that for ISa-RMSA, the light-forest-based approach can use less bandwidth than the light-tree-based one, while still satisfying the quality of transmission requirement. Therefore, we establish the minimum light-forest problem for optimizing a light-forest in ISa-RMSA. Finally, we design several time-efficient ISa-RMSA algorithms, and prove that one of them can solve the minimum light-forest problem with a fixed approximation ratio.
  - pub1:
    title: Novel Location-Constrained Virtual Network Embedding (LC-VNE) Algorithms Towards Integrated Node and Link Mapping
    authors: ["Long Gong", "Huihui Jiang", "Yixiang Wang", "Zuqing Zhu"]
    journal: IEEE/ACM Transactions on Networking
    type: journal
    pdf: http://zuqingzhu.info/pub_doc/2016/07432000.pdf
    url: http://ieeexplore.ieee.org/document/7432000/
    abstract: This paper tries to solve the location-constrained virtual network embedding (LC-VNE) problem efficiently. We first investigate the complexity of LC-VNE, and by leveraging the graph bisection problem, we provide the first formal proof of the  -completeness and inapproximability result of LC-VNE. Then, we propose two novel LC-VNE algorithms based on a compatibility graph (CG) to achieve integrated node and link mapping. In particular, in the CG, each node represents a candidate substrate path for a virtual link, and each link indicates the compatible relation between its two endnodes. Our theoretical analysis proves that the maximal clique in the CG is also the maximum one when the substrate network has sufficient resources. With CG, we reduce LC-VNE to the minimum-cost maximum clique problem, which inspires us to propose two efficient LC-VNE heuristics. Extensive numerical simulations demonstrate that compared with the existing ones, our proposed LC-VNE algorithms have significantly reduced time complexity and can provide smaller gaps to the optimal solutions, lower blocking probabilities, and higher time-average revenue as well.

experiences:
  - exp2:
    institution: AT&amp;T Labs Research 
    mentor: ["He Yan", "Zihui Ge"]
    started: 2016
    duration: (05/2016 - 07/2016)
    address: Bedminster, NJ, USA
    position: Research Intern
    description: Developed tools to automate the dynamics analysis in services supported by virtualized environment.
  - exp1:
    institution: NanYang Technological University
    mentor: ["Yonggang Wen"]
    started: 2012
    duration: (02/2012 - 06/2012)
    position: Visiting Student
    address: Singapore
    description: Designed a novel virtual network embedding algorithm, which increased the network utilization and decreased the time complexity. (INFOCOM 2014)

projects:
  - proj4:
    name: Refining Data Flow Information Using Infeasible Path
    description: This is a compiler course project. Details are available <a herf="https://github.com/saber-dragon/DemandDrivenDefUseAnalysis" target="_blank">here</a>
  - proj3:
    name: Path-sensitive Data-flow Analysis
    description: This is a compiler course project. Details are available <a herf="https://github.com/saber-dragon/PathSensitiveDataAnalysis" target="_blank">here</a>.
  - proj2:
    name: QPS
    description: A simple yet effective general add-on approach to existing crossbar scheduling algorithms, which could boost the performance (throughput or delay or both) of existing scheduling algorithms with "nearly no" computational overhead
  - proj1:
    name: ForestStream
    description: A hybrid graph streaming-sampling algorithm to measure the statistic properties of online social networking (OSN) cascades with high accuracy by using limited amount of memory


teaching:
  - t2:
    name: CS 3251 Computer Networking I
    url: https://piazza.com/gatech/cs3251a
  - t1:
    name: CS7260 Design &amp; Analysis of Network/Router Algorithms &amp; Hardware
    url: http://www.cc.gatech.edu/classes/AY2017/cs7260_spring

service:
  - s1: 
    type: Reviewer
    details: 
      - "<a href='https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=90' target='_blank'>IEEE/ACM Transactions on Networking</a>"
      - "IEEE INFOCOM 2016 (secondary reviewer)"
      - "<a href='http://www.comsoc.org/cl' target='_blank'>IEEE Communication Letters</a>"
      - "<a href='https://www.computer.org/web/tpds' target='_blank'>IEEE Transactions on Parallel and Distributed Systems</a>"


programmingSkills:
  - skill1:
    name: C/C++
    percentage: 88%
    packages:
      - pack0:
        name: Google Benchmark
        url: https://github.com/google/benchmark
      - pack1:
        name: Google Test 
        url: https://github.com/google/googletest
      - pack2:
        name: LEMON (Graph library)
        url: https://lemon.cs.elte.hu/trac/lemon
      - pack3:
        name: JSON for Modern C++
        url: https://github.com/nlohmann/json
      - pack4:
        name: fmt (formating library for C++)
        url: https://github.com/fmtlib/fmt
      - pack5:
        name: HdrHistogram 
        url: https://github.com/HdrHistogram/HdrHistogram_c
  - skill2:
    name: Python
    percentage: 75%
  - skill3:
    name: MATLAB
    percentage: 75%
  - skill4:
    name: LaTeX
    percentage: 70%
  - skill5:
    name: Java
    percentage: 50%
  # - skill6:
  #   name: PHP, HTML, JavaScript, CSS
  #   percentage: 20%

courses:
  finished:
    - c8:
      name: CS 6241 - Compiler Design 
    - c7:
      name: CS 6210 - Advanced Operating Systems
      url: https://www.udacity.com/wiki/ud156
    - c6:
      name: CS 7646 - Machine Learning for Trading
      url: https://www.udacity.com/course/machine-learning-for-trading--ud501
    - c5:
      name: MATH 6338 - Real Analysis II 
      url: http://people.math.gatech.edu/~heil/6338/summer08/
    - c4: 
      name: MATH 6761 - Stochastic Process I 
      url: https://www.math.gatech.edu/courses/math/6761
    - c4: 
      name: MATH 6337 - Real Analysis I 
      url: http://people.math.gatech.edu/~bwick6/teaching/math6337.html
    - c3:
      name: CS 7260 - Network Algorithmics
      url: https://www.cc.gatech.edu/classes/AY2017/cs7260_spring/
    - c2:
      name: CS 6505 - Computability &amp; Algorithms 
      url: https://www.cc.gatech.edu/classes/AY2010/cs6505_spring/
    - c1:
      name: CS 6250 - Computer Networks 
      url: https://www.cc.gatech.edu/~ammar/6250-Spring2013/
  interested:
    - c4: 
      name: GT CS 6290 - High Performance Computer Architecture
      url: https://www.youtube.com/playlist?list=PL6ogFv-ieghdoGKGg2Bik3Gl1glBTEu8c
    - c3:
      name: MIT 6.854 - Advanced Algorithms (Spring 2016)
      url: https://www.youtube.com/playlist?list=PL6ogFv-ieghdoGKGg2Bik3Gl1glBTEu8c
    - c2:
      name: Machine Learning on Coursera by Andrew Ng 
      url: https://www.coursera.org/learn/machine-learning
    - c1:
      name: UMass Amherst CS 377 Operting Systems (Spring 2014)
      url: https://www.youtube.com/watch?v=dv4mXBsv6TI&list=PLacuG5pysFbDQU8kKxbUh4K5c1iL5_k7k




references:
  - ref1:
    name: resumecard
    url: https://ddbullfrog.github.io/resumecard
    page: about
  - ref2:
    name: Jekyll-pithy
    url: https://github.com/jaylinwang/jekyll-pithy/tree/gh-pages
    page: blog
  - ref3:
    name: stanley-freelancer-theme
    url: http://blacktie.co/2014/01/stanley-freelancer-theme/
    page: home


# Gems
gems: [jekyll-paginate]